import type { Metadata } from "next";
import { Lexend, EB_Garamond } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} ${ebGaramond.variable} antialiased`}>
        <div style={{ display: "flex", minHeight: "100vh" }}>
          <Sidebar />
          <main style={{ flex: 1, paddingLeft: 32 }}>{children}</main>
        </div>
      </body>
    </html>
  );
}
